apiVersion: v1
kind: Service
metadata:
  name: konga-proxy
  namespace: kong
spec:
  type: LoadBalancer
  loadBalancerIP: 35.240.189.208
  ports:
  - name: konga-proxy
    port: 80
    targetPort: 1337
    nodePort: 31031
    protocol: TCP
  selector:
    app: konga
