apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kong
type: Opaque
data:
  # Default user is "kong_user".
  # Default password is "_1_1ove_bangk0k_".
  user: a29uZ191c2Vy
  password: XzFfMW92ZV9iYW5nazBrXw==
