apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  type: LoadBalancer
  ports:
  - name: kong-proxy
    port: 80
    targetPort: 8000
    nodePort: 30737
    protocol: TCP
  - name: kong-proxy-ssl
    port: 443
    targetPort: 8443
    nodePort: 30276
    protocol: TCP
  selector:
    app: kong
